//
// Generated file, do not edit! Created by opp_msgc 4.4 from messages/WSN_XY_ApplPkt.msg.
//

#ifndef _WSN_XY_APPLPKT_M_H_
#define _WSN_XY_APPLPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ApplPkt_m.h"
// }}



/**
 * Class generated from <tt>messages/WSN_XY_ApplPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet WSN_XY_ApplPkt extends ApplPkt {
 *     int i;
 *     int j;
 *     int u;
 *     int v;
 * }
 * </pre>
 */
class WSN_XY_ApplPkt : public ::ApplPkt
{
  protected:
    int i_var;
    int j_var;
    int u_var;
    int v_var;

  private:
    void copy(const WSN_XY_ApplPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WSN_XY_ApplPkt&);

  public:
    WSN_XY_ApplPkt(const char *name=NULL, int kind=0);
    WSN_XY_ApplPkt(const WSN_XY_ApplPkt& other);
    virtual ~WSN_XY_ApplPkt();
    WSN_XY_ApplPkt& operator=(const WSN_XY_ApplPkt& other);
    virtual WSN_XY_ApplPkt *dup() const {return new WSN_XY_ApplPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getI() const;
    virtual void setI(int i);
    virtual int getJ() const;
    virtual void setJ(int j);
    virtual int getU() const;
    virtual void setU(int u);
    virtual int getV() const;
    virtual void setV(int v);
};

inline void doPacking(cCommBuffer *b, WSN_XY_ApplPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, WSN_XY_ApplPkt& obj) {obj.parsimUnpack(b);}


#endif // _WSN_XY_APPLPKT_M_H_
